name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s by %an")
          PAYLOAD="{\"content\": \"🚀 Nový commit na *main*: $COMMIT_MSG\"}"
          curl -X POST -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            ${{ secrets.DISCORD_WEBHOOK }}
